version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - .:/data

  web:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/data

volumes:
  db-store:
